# Generated by Django 5.2.1 on 2026-03-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweet",
            name="text",
            field=models.CharField(max_length=280),
        ),
    ]
